language: python
cache: pip
python:
  - '3.6'
  # - '3.5'
  - '3.4'
install:
  - pip install .
  - pip install pytest-cov codecov
script:
  - pytest --cov=./bert_embedding
notifications:
  email: false
after_success:
  - codecov
# deploy:
#   provider: pypi
#   distributions: sdist bdist_wheel
#   user: mrahman
#   password: "$PYPI_PW"
#   on:
#     repo: mrsumitbd/bert-embedding
#     python: 3.4
#     branch: master
