language: python
cache: pip
python:
  - '3.4'
  - '3.5'
  - '3.6'
install:
  - pip install .
  - pip install pytest-cov codecov
script:
  - pytest --cov=./bert_embedding
notifications:
  email: false
after_success:
  - codecov
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: mrahman
  password: pypi-AgEIcHlwaS5vcmcCJDg4ZTBlNzJjLTZmNDUtNDVhMS05YWU0LWU5MWQ2NGViOTdiZAACKlszLCIzNGVlYWRkZi1jMjgwLTQ4NDctYWMyOC0zMmUzMmE3ZmY5YzYiXQAABiDPHHxC2VJnjnHlMnvchbVqA6opFrTPwZfteUPn50mmKw
  on:
    repo: mrsumitbd/bert-embedding
    python: 3.5
    branch: master
